# Generated by Django 4.1.3 on 2022-12-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_reply_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
